- name: set timezone to Moscow
  timezone:
    name: Europe/Moscow


- name: update cache
  ansible.builtin.yum:
    update_cache: true

- name: Install base tools
  ansible.builtin.yum:
    name:
    - vim
    - traceroute
    - tcpdump
    state: latest

