- name: Set up NAT on inetRouter
  block:
    - name: disable and stop firewalld
      service:
        name: firewalld
        state: stopped
        enabled: false
    - name: install iptables
      yum:
        name:
        - iptables
        - iptables-services
        state: present
        update_cache: true
    
    - name: copy inetRouter_iptables config
      template: 
        src: inetRouter_iptables
        dest: /etc/sysconfig/iptables
        owner: root
        group: root
        mode: 0600
      when: (ansible_hostname == "inetRouter")

    - name: copy inetRouter2_iptables config
      template: 
        src: inetRouter2_iptables
        dest: /etc/sysconfig/iptables
        owner: root
        group: root
        mode: 0600
      when: (ansible_hostname == "inetRouter2")

    - name: start and enable iptables service
      service: 
          name: iptables
          state: restarted
          enabled: true
  when: (ansible_hostname == "inetRouter" or ansible_hostname == "inetRouter2")

- name: set up forward packages across routers
  sysctl:
    name: net.ipv4.conf.all.forwarding
    value: '1'
    state: present
    reload: true
  when: "'routers' in group_names"

- name: set up forward packages across routers
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: true
  when: "'routers' in group_names"

# echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0  
- name: disable default route
  lineinfile: 
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0  
    line: DEFROUTE=NO
  when: (ansible_hostname != "inetRouter" and ansible_hostname != "inetRouter2")

- name: add default gateway for centralRouter
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
    line: GATEWAY=192.168.255.1
  when: (ansible_hostname == "centralRouter")

- name: add default gateway for centralServer
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
    line: GATEWAY=192.168.0.1
  when: (ansible_hostname == "centralServer")

- name: set up route on inetRouter
  template:
    src: inetRouter_route_eth1.j2
    dest: /etc/sysconfig/network-scripts/route-eth1
    owner: root
    group: root
    mode: 0644
  when: (ansible_hostname == "inetRouter")

- name: set up route on inetRouter2
  template:
    src: inetRouter_route_eth1.j2
    dest: /etc/sysconfig/network-scripts/route-eth1
    owner: root
    group: root
    mode: 0644
  when: (ansible_hostname == "inetRouter2")

- name: set up route on centralRouter eth1
  template:
    src: centralRouter_route_eth1.j2
    dest: /etc/sysconfig/network-scripts/route-eth1
    owner: root
    group: root
    mode: 0644
  when: (ansible_hostname == "centralRouter")

- name: set up route on centralRouter eth2
  template:
    src: centralRouter_route_eth2.j2
    dest: /etc/sysconfig/network-scripts/route-eth2
    owner: root
    group: root
    mode: 0644
  when: (ansible_hostname == "centralRouter")

- name: set up route on centralRouter eth3
  template:
    src: centralRouter_route_eth3.j2
    dest: /etc/sysconfig/network-scripts/route-eth3
    owner: root
    group: root
    mode: 0644
  when: (ansible_hostname == "centralRouter")

- name: restart network
  service: 
    name: network
    state: restarted

- name: restart network
  service: 
    name: network
    state: restarted
